server:
  port: 8040

info:
  artifactId: "${project.name}"
  version: "${project.version}"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/analysis?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: '12345678'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none

integration:
  notification-client:
    baseUrl: http://localhost:8030
  footballapi-client:
    base-url: https://api-football-v1.p.rapidapi.com/v3


feign:
  client:
    config:
      FootballApiClient:
        #        connectTimeout: 5000
        #        readTimeout: 5000
        #        loggerLevel: full
        #        errorDecoder: com.example.SimpleErrorDecoder
        #        retryer: com.example.SimpleRetryer
        #        defaultQueryParameters:
        #          query: queryValue
        defaultRequestHeaders:
          x-rapidapi-host: api-football-v1.p.rapidapi.com
          x-rapidapi-key: 685d607beemsh50243298388893ep13a200jsndf3842b4e86d
    #        requestInterceptors:
    #          - com.example.FooRequestInterceptor
    #          - com.example.BarRequestInterceptor
    #        decode404: false
    #        encoder: com.example.SimpleEncoder
    #        decoder: com.example.SimpleDecoder
    #        contract: com.example.SimpleContract
    #        capabilities:
    #          - com.example.FooCapability
    #          - com.example.BarCapability
    #        metrics.enabled: false
